name: Rust Vocab CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Unit tests
        run: cargo test --bins --lib

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt -- --check