name: Rust Vocab CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Unit tests
        run: cargo test --bins --lib --verbose

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Set up Docker Compose
        run: docker-compose -f test-database/docker-compose.yml up -d

      - name: Run integration tests
        run: cargo test -- --test-threads 1

      - name: Shutdown Docker Compose
        run: docker-compose -f docker-compose.yml down
